#! /bin/sh

chat=/tmp/tokencli.chatter
token=/tmp/tokencli.token
trap "rm -f $chat $token" 0

mkfifo -m 0500 $chat $token

while true; do
    for dn in /opt/*/tokencli/*; do
        [ -d $dn ] || continue
        puzzle=$(basename $dn)
        category=$(cat $dn/category)
        nc 10.0.0.1 1 < $fifo | tokencli $category $dn/category.key > $fifo 3> $token
        arc4 $dn/enc.key < $token > /var/lib/ctf/tokens/$category
    done
    sleep 60
done
