#! /bin/sh

if [ ! -d /opt/mcp ]; then
    hostname pwnables
fi

# Set up a chroot environment by duplicating the base
# image
if [ ! -x /mnt/pwnables-root/bin/busybox ]; then
    mkdir -p /mnt/pwnables-root
    mount -o bind / /mnt/pwnables-root
    mount -t tmpfs -o size=5m,mode=0755 pwnables-var /mnt/pwnables-root/var
    mount -t tmpfs -o size=15k pwnables-tmp /mnt/pwnables-root/tmp
    mount -t tmpfs -o size=5m pwnables-home /mnt/pwnables-root/home

    # Make some skeleton junk
    install -o root -m 0755 -d /mnt/pwnables-root/var/lib
    install -o root -m 0755 -d /mnt/pwnables-root/var/log
    install -o root -m 0755 -d /mnt/pwnables-root/var/spool
    install -o root -m 0755 -d /mnt/pwnables-root/var/cache
    install -o root -m 0777 -d /mnt/pwnables-root/var/run
    install -o root -m 0777 -d /mnt/pwnables-root/var/cache

    install -o root -d /mnt/pwnables-root/home/alice/
    install -o root -m 0111 bin/* /mnt/pwnables-root/home/alice/

    # ltrace needs to read the binary
    chmod +r /mnt/pwnables-root/home/alice/ltraceme

    # strace needs to be suid
    chown bob /mnt/pwnables-root/home/alice/straceme
    chmod 04511 /mnt/pwnables-root/home/alice/straceme
fi

cp -r service/* /var/service/
