#! /bin/sh

BASEURL=http://localhost:8080

case "$1" in
  a)
    URL=$BASEURL/answer
    ;;
  b)
    URL=$BASEURL/puzzles.json
    ;;
  *)
    echo "Usage: $0 a|b" 1>&2
    exit 1
    ;;
esac

while true; do
  curl \
    -X POST \
    -F "cat=base" \
    -F "points=1" \
    -F "id=test" \
    -F "answer=moo" \
    $URL
done
