#! /bin/sh

## Run two of these to trigger the race condition from

BASEURL=http://localhost:8080
URL=$BASEURL/answer

while true; do
  curl \
    -X POST \
    -F "cat=byobf" \
    -F "points=10" \
    -F "id=test" \
    -F "answer=6" \
    $URL
done
