stages:
  - test
  - push

test:
  stage: test
  image: golang:1.17
  only:
    refs:
      - main
      - merge_requests
  script:
    - go test ./...

push:
  stage: push
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  rules:
    - if: $CI_COMMIT_TAG
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  script:
    - mkdir -p /kaniko/.docker
    - echo "$DOCKER_AUTH_CONFIG" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/build/package/Containerfile --destination ghcr.io/dirtbags/moth:$CI_COMMIT_REF_SLUG
