stages:
  - test
  - push

test:
  stage: test
  image: golang:1.17
  script:
    - go test -race ./...

push:
  stage: push
  rules:
    - if: $CI_COMMIT_TAG
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  script:
    - mkdir ~/.docker
    - echo "$DOCKER_AUTH_CONFIG" > ~/.docker/config.json
    - sh build/ci/ci.sh publish
    - >
      docker build 
      --tag ghcr.io/dirtbags/moth:$CI_COMMIT_REF_SLUG
      --file build/package/Containerfile
      .
