stages:
  - test
  - push

test:
  image: golang:1.17
  only:
    refs:
      - main
      - merge_requests
  stage: test
  script:
    - go test ./...

push:
  stage: push
  rules:
    - if: $CI_COMMIT_TAG
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  script:
    - ./ci.sh push
