FROM alpine

ARG http_proxy
ENV http_proxy=${http_proxy}

RUN apk --no-cache add python3 py3-pillow

COPY tools/package-puzzles.py tools/moth.py tools/mistune.py tools/answer_words.txt /moth/

ENTRYPOINT ["python3", "/moth/package-puzzles.py"]
