FROM alpine

RUN apk --no-cache add python3 py3-pillow

COPY tools/package-puzzles.py /pp/
COPY tools/moth.py /pp/
COPY tools/mistune.py /pp/
COPY tools/answer_words.txt /pp/

ENTRYPOINT ["python3", "/pp/package-puzzles.py"]
