FROM python:3.7.2-alpine3.9

RUN apk --no-cache add \
      gcc \
      musl-dev \
      jpeg-dev \
      zlib-dev \
    && \
    pip3 install pillow

COPY devel /app/
COPY example-puzzles /puzzles/
COPY theme /theme/

WORKDIR /moth/
ENTRYPOINT [ "python3", "/app/devel-server.py" ]
CMD [ "--bind", "0.0.0.0:8080", "--puzzles", "/puzzles", "--theme", "/theme" ]
