FROM alpine

ARG http_proxy
ENV http_proxy=${http_proxy}

RUN apk --no-cache add python3 py3-pillow

COPY tools/devel-server.py tools/moth.py tools/mistune.py tools/answer_words.txt /moth/
COPY www /moth/src/www
COPY example-puzzles /moth/puzzles
COPY docs /moth/docs

WORKDIR /moth/
ENTRYPOINT ["python3", "/moth/devel-server.py"]
