FROM alpine:3.8

RUN apk --no-cache add \
    gcc \
    musl-dev \
    python3 \
    python3-dev \
    py3-pillow \
  && pip3 install aiohttp

COPY devel /app/
COPY example-puzzles /puzzles/
COPY theme /theme/

WORKDIR /moth/
ENTRYPOINT [ "python3", "/app/devel-server.py" ]
CMD [ "--bind", "0.0.0.0:8080", "--puzzles", "/puzzles", "--theme", "/theme" ]
