#! /bin/sh /etc/rc.common

START=41
STOP=89

VLANS=48

start () {
    for i in $(seq 1 $VLANS); do
        vconfig add eth0 $i
        ifconfig eth0.$i 10.$i.0.1 netmask 255.255.0.0
    done
}

stop () {
    for i in $(seq 1 $VLANS); do
        vconfig rem eth0.$i
    done
}

