#! /bin/sh

[ -f /var/lib/ctf/disabled/tanks ] && exit 0

ln -s /var/lib/tanks /usr/lib/www/tanks/results

exec envuidgid ctf python2.6 run_tanks.py /var/lib/tanks/ easy 100  2>&1 &
#envuidgid ctf report_score.py 2>&1
