#! /bin/sh

cd ${1:-$(dirname $0)}
MOTH_BASE=$(pwd)

echo "Running moth instances in $MOTH_BASE"

while true; do
	for i in $MOTH_BASE/*/assigned.txt; do
		dir=${i%/*}
		$dir/bin/once
	done
	sleep 5
done
